"""Change user is_superuser to Enum type

Revision ID: 02ed92d720fc
Revises: b9a123f55fe2
Create Date: 2025-08-09 19:02:19.909489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02ed92d720fc"
down_revision: Union[str, Sequence[str], None] = "b9a123f55fe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_superuser",
            sa.Enum("ADMIN", "USER", name="userrole", native_enum=False),
            server_default="N",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_superuser")
    # ### end Alembic commands ###
